const Ziggy = {
    url: 'http:\/\/mrs-beauty.test',
    port: null,
    defaults: {},
    routes: {
        'horizon.stats.index': { uri: 'horizon\/api\/stats', methods: ['GET', 'HEAD'] },
        'horizon.workload.index': { uri: 'horizon\/api\/workload', methods: ['GET', 'HEAD'] },
        'horizon.masters.index': { uri: 'horizon\/api\/masters', methods: ['GET', 'HEAD'] },
        'horizon.monitoring.index': { uri: 'horizon\/api\/monitoring', methods: ['GET', 'HEAD'] },
        'horizon.monitoring.store': { uri: 'horizon\/api\/monitoring', methods: ['POST'] },
        'horizon.monitoring-tag.paginate': { uri: 'horizon\/api\/monitoring\/{tag}', methods: ['GET', 'HEAD'], parameters: ['tag'] },
        'horizon.monitoring-tag.destroy': { uri: 'horizon\/api\/monitoring\/{tag}', methods: ['DELETE'], wheres: { tag: '.*' }, parameters: ['tag'] },
        'horizon.jobs-metrics.index': { uri: 'horizon\/api\/metrics\/jobs', methods: ['GET', 'HEAD'] },
        'horizon.jobs-metrics.show': { uri: 'horizon\/api\/metrics\/jobs\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.queues-metrics.index': { uri: 'horizon\/api\/metrics\/queues', methods: ['GET', 'HEAD'] },
        'horizon.queues-metrics.show': { uri: 'horizon\/api\/metrics\/queues\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.jobs-batches.index': { uri: 'horizon\/api\/batches', methods: ['GET', 'HEAD'] },
        'horizon.jobs-batches.show': { uri: 'horizon\/api\/batches\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.jobs-batches.retry': { uri: 'horizon\/api\/batches\/retry\/{id}', methods: ['POST'], parameters: ['id'] },
        'horizon.pending-jobs.index': { uri: 'horizon\/api\/jobs\/pending', methods: ['GET', 'HEAD'] },
        'horizon.completed-jobs.index': { uri: 'horizon\/api\/jobs\/completed', methods: ['GET', 'HEAD'] },
        'horizon.silenced-jobs.index': { uri: 'horizon\/api\/jobs\/silenced', methods: ['GET', 'HEAD'] },
        'horizon.failed-jobs.index': { uri: 'horizon\/api\/jobs\/failed', methods: ['GET', 'HEAD'] },
        'horizon.failed-jobs.show': { uri: 'horizon\/api\/jobs\/failed\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.retry-jobs.show': { uri: 'horizon\/api\/jobs\/retry\/{id}', methods: ['POST'], parameters: ['id'] },
        'horizon.jobs.show': { uri: 'horizon\/api\/jobs\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.index': { uri: 'horizon\/{view?}', methods: ['GET', 'HEAD'], wheres: { view: '(.*)' }, parameters: ['view'] },
        pulse: { uri: 'pulse', methods: ['GET', 'HEAD'] },
        'default-livewire.update': { uri: 'livewire-3be60ca2\/update', methods: ['POST'] },
        'livewire.upload-file': { uri: 'livewire-3be60ca2\/upload-file', methods: ['POST'] },
        'livewire.preview-file': { uri: 'livewire-3be60ca2\/preview-file\/{filename}', methods: ['GET', 'HEAD'], parameters: ['filename'] },
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'settings\/profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'settings\/profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'settings\/profile', methods: ['DELETE'] },
        'password.edit': { uri: 'settings\/password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'settings\/password', methods: ['PUT'] },
        appearance: { uri: 'settings\/appearance', methods: ['GET', 'HEAD'] },
        'team.index': { uri: 'settings\/team', methods: ['GET', 'HEAD'] },
        'team.update': { uri: 'settings\/team\/{member}', methods: ['PATCH'], parameters: ['member'], bindings: { member: 'uuid' } },
        'team.deactivate': { uri: 'settings\/team\/{member}', methods: ['DELETE'], parameters: ['member'], bindings: { member: 'uuid' } },
        'team.reactivate': { uri: 'settings\/team\/{member}\/reaktivieren', methods: ['PUT'], parameters: ['member'], bindings: { member: 'uuid' } },
        'invitations.store': { uri: 'settings\/team\/einladungen', methods: ['POST'] },
        'invitations.resend': {
            uri: 'settings\/team\/einladungen\/{invitation}\/erneut',
            methods: ['POST'],
            parameters: ['invitation'],
            bindings: { invitation: 'uuid' },
        },
        'invitations.destroy': {
            uri: 'settings\/team\/einladungen\/{invitation}',
            methods: ['DELETE'],
            parameters: ['invitation'],
            bindings: { invitation: 'uuid' },
        },
        'locations.index': { uri: 'settings\/standorte', methods: ['GET', 'HEAD'] },
        'locations.store': { uri: 'settings\/standorte', methods: ['POST'] },
        'locations.update': { uri: 'settings\/standorte\/{location}', methods: ['PATCH'], parameters: ['location'], bindings: { location: 'uuid' } },
        'locations.deactivate': {
            uri: 'settings\/standorte\/{location}',
            methods: ['DELETE'],
            parameters: ['location'],
            bindings: { location: 'uuid' },
        },
        'locations.activate': {
            uri: 'settings\/standorte\/{location}\/aktivieren',
            methods: ['PUT'],
            parameters: ['location'],
            bindings: { location: 'uuid' },
        },
        'closures.store': {
            uri: 'settings\/standorte\/{location}\/schliesszeiten',
            methods: ['POST'],
            parameters: ['location'],
            bindings: { location: 'uuid' },
        },
        'closures.destroy': {
            uri: 'settings\/standorte\/{location}\/schliesszeiten\/{closure}',
            methods: ['DELETE'],
            parameters: ['location', 'closure'],
            bindings: { location: 'uuid', closure: 'uuid' },
        },
        'practitioners.index': { uri: 'settings\/behandler', methods: ['GET', 'HEAD'] },
        'practitioners.store': { uri: 'settings\/behandler', methods: ['POST'] },
        'practitioners.update': {
            uri: 'settings\/behandler\/{practitioner}',
            methods: ['PATCH'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.deactivate': {
            uri: 'settings\/behandler\/{practitioner}',
            methods: ['DELETE'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.activate': {
            uri: 'settings\/behandler\/{practitioner}\/aktivieren',
            methods: ['PUT'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'workinghours.store': {
            uri: 'settings\/behandler\/{practitioner}\/arbeitszeiten',
            methods: ['POST'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'workinghours.destroy': {
            uri: 'settings\/behandler\/{practitioner}\/arbeitszeiten\/{workingHour}',
            methods: ['DELETE'],
            parameters: ['practitioner', 'workingHour'],
            bindings: { practitioner: 'uuid', workingHour: 'uuid' },
        },
        'absences.store': {
            uri: 'settings\/behandler\/{practitioner}\/abwesenheiten',
            methods: ['POST'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'absences.destroy': {
            uri: 'settings\/behandler\/{practitioner}\/abwesenheiten\/{absence}',
            methods: ['DELETE'],
            parameters: ['practitioner', 'absence'],
            bindings: { practitioner: 'uuid', absence: 'uuid' },
        },
        'treatments.index': { uri: 'settings\/behandlungen', methods: ['GET', 'HEAD'] },
        'treatments.store': { uri: 'settings\/behandlungen', methods: ['POST'] },
        'treatments.update': {
            uri: 'settings\/behandlungen\/{treatment}',
            methods: ['PATCH'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'treatments.deactivate': {
            uri: 'settings\/behandlungen\/{treatment}',
            methods: ['DELETE'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'treatments.activate': {
            uri: 'settings\/behandlungen\/{treatment}\/aktivieren',
            methods: ['PUT'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'appointmenttypes.index': { uri: 'settings\/terminarten', methods: ['GET', 'HEAD'] },
        'appointmenttypes.store': { uri: 'settings\/terminarten', methods: ['POST'] },
        'appointmenttypes.update': {
            uri: 'settings\/terminarten\/{appointmentType}',
            methods: ['PATCH'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'appointmenttypes.deactivate': {
            uri: 'settings\/terminarten\/{appointmentType}',
            methods: ['DELETE'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'appointmenttypes.activate': {
            uri: 'settings\/terminarten\/{appointmentType}\/aktivieren',
            methods: ['PUT'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'audit.index': { uri: 'settings\/protokoll', methods: ['GET', 'HEAD'] },
        'impersonation.store': { uri: 'impersonation', methods: ['POST'] },
        'impersonation.destroy': { uri: 'impersonation', methods: ['DELETE'] },
        'impersonation.approve': {
            uri: 'impersonation\/{session}\/freigeben',
            methods: ['POST'],
            parameters: ['session'],
            bindings: { session: 'uuid' },
        },
        'invitations.show': { uri: 'einladung\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'invitations.accept': { uri: 'einladung\/{token}', methods: ['POST'], parameters: ['token'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email\/{id}\/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'storage.local': { uri: 'storage\/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
        'storage.local.upload': { uri: 'storage\/{path}', methods: ['PUT'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
