const Ziggy = {
    url: 'http:\/\/mrs-beauty.test',
    port: null,
    defaults: {},
    routes: {
        pulse: { uri: 'pulse', methods: ['GET', 'HEAD'] },
        'default-livewire.update': { uri: 'livewire-3be60ca2\/update', methods: ['POST'] },
        'livewire.upload-file': { uri: 'livewire-3be60ca2\/upload-file', methods: ['POST'] },
        'livewire.preview-file': { uri: 'livewire-3be60ca2\/preview-file\/{filename}', methods: ['GET', 'HEAD'], parameters: ['filename'] },
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'buchung.zeigen': { uri: 'buchen\/{praxis}', methods: ['GET', 'HEAD'], parameters: ['praxis'] },
        'buchung.reservieren': { uri: 'buchen\/{praxis}\/reservieren', methods: ['POST'], parameters: ['praxis'] },
        'buchung.freigeben': { uri: 'buchen\/{praxis}\/reservieren', methods: ['DELETE'], parameters: ['praxis'] },
        'buchung.buchen': { uri: 'buchen\/{praxis}', methods: ['POST'], parameters: ['praxis'] },
        'buchung.bestaetigt': { uri: 'buchen\/{praxis}\/bestaetigt', methods: ['GET', 'HEAD'], parameters: ['praxis'] },
        'buchung.logo': { uri: 'buchen\/{praxis}\/logo', methods: ['GET', 'HEAD'], parameters: ['praxis'] },
        'buchung.einwilligung': { uri: 'buchen\/{praxis}\/einwilligung', methods: ['POST'], parameters: ['praxis'] },
        'mail.logo': { uri: 'mail\/logo\/{fassung}', methods: ['GET', 'HEAD'], wheres: { fassung: '[0-9]+' }, parameters: ['fassung'] },
        'appointments.index': { uri: 'termine', methods: ['GET', 'HEAD'] },
        'appointments.store': { uri: 'termine', methods: ['POST'] },
        'appointments.reschedule': {
            uri: 'termine\/{appointment}\/verschieben',
            methods: ['PATCH'],
            parameters: ['appointment'],
            bindings: { appointment: 'uuid' },
        },
        'appointments.status': {
            uri: 'termine\/{appointment}\/status',
            methods: ['PATCH'],
            parameters: ['appointment'],
            bindings: { appointment: 'uuid' },
        },
        'appointments.cancel': { uri: 'termine\/{appointment}', methods: ['DELETE'], parameters: ['appointment'], bindings: { appointment: 'uuid' } },
        'locations.index': { uri: 'standorte', methods: ['GET', 'HEAD'] },
        'locations.store': { uri: 'standorte', methods: ['POST'] },
        'locations.update': { uri: 'standorte\/{location}', methods: ['PATCH'], parameters: ['location'], bindings: { location: 'uuid' } },
        'locations.deactivate': { uri: 'standorte\/{location}', methods: ['DELETE'], parameters: ['location'], bindings: { location: 'uuid' } },
        'locations.activate': {
            uri: 'standorte\/{location}\/aktivieren',
            methods: ['PUT'],
            parameters: ['location'],
            bindings: { location: 'uuid' },
        },
        'closures.store': {
            uri: 'standorte\/{location}\/schliesszeiten',
            methods: ['POST'],
            parameters: ['location'],
            bindings: { location: 'uuid' },
        },
        'closures.destroy': {
            uri: 'standorte\/{location}\/schliesszeiten\/{closure}',
            methods: ['DELETE'],
            parameters: ['location', 'closure'],
            bindings: { location: 'uuid', closure: 'uuid' },
        },
        'practitioners.index': { uri: 'behandler', methods: ['GET', 'HEAD'] },
        'practitioners.store': { uri: 'behandler', methods: ['POST'] },
        'practitioners.update': {
            uri: 'behandler\/{practitioner}',
            methods: ['PATCH'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.deactivate': {
            uri: 'behandler\/{practitioner}',
            methods: ['DELETE'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.activate': {
            uri: 'behandler\/{practitioner}\/aktivieren',
            methods: ['PUT'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.avatar.store': {
            uri: 'behandler\/{practitioner}\/bild',
            methods: ['POST'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'practitioners.avatar.destroy': {
            uri: 'behandler\/{practitioner}\/bild',
            methods: ['DELETE'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'workinghours.store': {
            uri: 'behandler\/{practitioner}\/arbeitszeiten',
            methods: ['POST'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'workinghours.destroy': {
            uri: 'behandler\/{practitioner}\/arbeitszeiten\/{workingHour}',
            methods: ['DELETE'],
            parameters: ['practitioner', 'workingHour'],
            bindings: { practitioner: 'uuid', workingHour: 'uuid' },
        },
        'absences.store': {
            uri: 'behandler\/{practitioner}\/abwesenheiten',
            methods: ['POST'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'absences.destroy': {
            uri: 'behandler\/{practitioner}\/abwesenheiten\/{absence}',
            methods: ['DELETE'],
            parameters: ['practitioner', 'absence'],
            bindings: { practitioner: 'uuid', absence: 'uuid' },
        },
        'treatments.index': { uri: 'behandlungen', methods: ['GET', 'HEAD'] },
        'treatments.store': { uri: 'behandlungen', methods: ['POST'] },
        'treatments.update': { uri: 'behandlungen\/{treatment}', methods: ['PATCH'], parameters: ['treatment'], bindings: { treatment: 'uuid' } },
        'treatments.deactivate': {
            uri: 'behandlungen\/{treatment}',
            methods: ['DELETE'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'treatments.activate': {
            uri: 'behandlungen\/{treatment}\/aktivieren',
            methods: ['PUT'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'treatments.hwg.uebersteuern': {
            uri: 'behandlungen\/{treatment}\/hwg-uebersteuern',
            methods: ['POST'],
            parameters: ['treatment'],
            bindings: { treatment: 'uuid' },
        },
        'appointmenttypes.index': { uri: 'terminarten', methods: ['GET', 'HEAD'] },
        'appointmenttypes.store': { uri: 'terminarten', methods: ['POST'] },
        'appointmenttypes.update': {
            uri: 'terminarten\/{appointmentType}',
            methods: ['PATCH'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'appointmenttypes.deactivate': {
            uri: 'terminarten\/{appointmentType}',
            methods: ['DELETE'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'appointmenttypes.activate': {
            uri: 'terminarten\/{appointmentType}\/aktivieren',
            methods: ['PUT'],
            parameters: ['appointmentType'],
            bindings: { appointmentType: 'uuid' },
        },
        'kalender.google.webhook': { uri: 'kalender\/google\/zustellung', methods: ['POST'] },
        'kalender.microsoft.webhook': { uri: 'kalender\/microsoft\/zustellung', methods: ['POST'] },
        'kalender.index': { uri: 'kalender', methods: ['GET', 'HEAD'] },
        'kalender.aktualisieren': { uri: 'kalender\/{verbindung}', methods: ['PATCH'], parameters: ['verbindung'], bindings: { verbindung: 'uuid' } },
        'kalender.abgleichen': {
            uri: 'kalender\/{verbindung}\/abgleichen',
            methods: ['POST'],
            parameters: ['verbindung'],
            bindings: { verbindung: 'uuid' },
        },
        'kalender.trennen': { uri: 'kalender\/{verbindung}', methods: ['DELETE'], parameters: ['verbindung'], bindings: { verbindung: 'uuid' } },
        'kalender.google.verbinden': {
            uri: 'kalender\/google\/{practitioner}\/verbinden',
            methods: ['GET', 'HEAD'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'kalender.google.rueckkehr': { uri: 'oauth\/google\/callback', methods: ['GET', 'HEAD'] },
        'kalender.microsoft.verbinden': {
            uri: 'kalender\/microsoft\/{practitioner}\/verbinden',
            methods: ['GET', 'HEAD'],
            parameters: ['practitioner'],
            bindings: { practitioner: 'uuid' },
        },
        'kalender.microsoft.rueckkehr': { uri: 'oauth\/microsoft\/callback', methods: ['GET', 'HEAD'] },
        'contacts.index': { uri: 'kontakte', methods: ['GET', 'HEAD'] },
        'contacts.store': { uri: 'kontakte', methods: ['POST'] },
        'contacts.update': { uri: 'kontakte\/{contact}', methods: ['PATCH'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'contacts.destroy': { uri: 'kontakte\/{contact}', methods: ['DELETE'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'contacts.export': { uri: 'kontakte\/{contact}\/auskunft', methods: ['GET', 'HEAD'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'identities.store': { uri: 'kontakte\/{contact}\/kanaele', methods: ['POST'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'identities.destroy': {
            uri: 'kontakte\/{contact}\/kanaele\/{identity}',
            methods: ['DELETE'],
            parameters: ['contact', 'identity'],
            bindings: { contact: 'uuid', identity: 'uuid' },
        },
        'contacts.merge': { uri: 'kontakte\/{contact}\/zusammenfuehren', methods: ['POST'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'contacts.notes.store': { uri: 'kontakte\/{contact}\/notizen', methods: ['POST'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'contacts.notes.destroy': {
            uri: 'kontakte\/{contact}\/notizen\/{note}',
            methods: ['DELETE'],
            parameters: ['contact', 'note'],
            bindings: { contact: 'uuid', note: 'uuid' },
        },
        'contacts.tags.store': { uri: 'kontakte\/{contact}\/schlagworte', methods: ['POST'], parameters: ['contact'], bindings: { contact: 'uuid' } },
        'contacts.tags.destroy': {
            uri: 'kontakte\/{contact}\/schlagworte\/{tag}',
            methods: ['DELETE'],
            parameters: ['contact', 'tag'],
            bindings: { contact: 'uuid', tag: 'uuid' },
        },
        'merges.revert': { uri: 'zusammenfuehrungen\/{merge}\/rueckgaengig', methods: ['POST'], parameters: ['merge'], bindings: { merge: 'uuid' } },
        'leads.index': { uri: 'anfragen', methods: ['GET', 'HEAD'] },
        'leads.store': { uri: 'anfragen', methods: ['POST'] },
        'leads.respond': { uri: 'anfragen\/{lead}\/reaktion', methods: ['POST'], parameters: ['lead'], bindings: { lead: 'uuid' } },
        'leads.lose': { uri: 'anfragen\/{lead}\/verloren', methods: ['POST'], parameters: ['lead'], bindings: { lead: 'uuid' } },
        'waitlist.index': { uri: 'warteliste', methods: ['GET', 'HEAD'] },
        'waitlist.store': { uri: 'warteliste', methods: ['POST'] },
        'waitlist.update': { uri: 'warteliste\/{entry}', methods: ['PATCH'], parameters: ['entry'], bindings: { entry: 'uuid' } },
        'waitlist.destroy': { uri: 'warteliste\/{entry}', methods: ['DELETE'], parameters: ['entry'], bindings: { entry: 'uuid' } },
        'waitlist.klaerung.uebergeben': {
            uri: 'warteliste\/klaerung\/{offer}\/uebergeben',
            methods: ['POST'],
            parameters: ['offer'],
            bindings: { offer: 'uuid' },
        },
        'waitlist.klaerung.behalten': {
            uri: 'warteliste\/klaerung\/{offer}\/behalten',
            methods: ['POST'],
            parameters: ['offer'],
            bindings: { offer: 'uuid' },
        },
        'privacy.index': { uri: 'datenschutz', methods: ['GET', 'HEAD'] },
        'privacy.policies.update': {
            uri: 'datenschutz\/fristen\/{policy}',
            methods: ['PATCH'],
            parameters: ['policy'],
            bindings: { policy: 'uuid' },
        },
        'privacy.enforce': { uri: 'datenschutz\/durchsetzen', methods: ['POST'] },
        'anhang.zeigen': { uri: 'anhaenge\/{attachment}', methods: ['GET', 'HEAD'], parameters: ['attachment'], bindings: { attachment: 'uuid' } },
        'meta.webhook.verify': { uri: 'webhooks\/meta', methods: ['GET', 'HEAD'] },
        'meta.webhook': { uri: 'webhooks\/meta', methods: ['POST'] },
        'mail.webhook': { uri: 'webhooks\/mail', methods: ['POST'] },
        'inbox.index': { uri: 'posteingang', methods: ['GET', 'HEAD'] },
        'inbox.reply': {
            uri: 'posteingang\/{conversation}\/antwort',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.template': {
            uri: 'posteingang\/{conversation}\/template',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.close': {
            uri: 'posteingang\/{conversation}\/schliessen',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.reopen': {
            uri: 'posteingang\/{conversation}\/oeffnen',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.assign': {
            uri: 'posteingang\/{conversation}\/zuordnen',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.agent': {
            uri: 'posteingang\/{conversation}\/agent',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'inbox.agent.fortsetzen': {
            uri: 'posteingang\/{conversation}\/agent\/fortsetzen',
            methods: ['POST'],
            parameters: ['conversation'],
            bindings: { conversation: 'uuid' },
        },
        'werbung.index': { uri: 'werbung', methods: ['GET', 'HEAD'] },
        'werbung.verbinden': { uri: 'werbung\/verbinden', methods: ['GET', 'HEAD'] },
        'werbung.rueckkehr': { uri: 'oauth\/meta\/callback', methods: ['GET', 'HEAD'] },
        'werbung.auswaehlen': { uri: 'werbung\/auswahl', methods: ['POST'] },
        'werbung.abgleichen': {
            uri: 'werbung\/{werbekonto}\/abgleichen',
            methods: ['POST'],
            parameters: ['werbekonto'],
            bindings: { werbekonto: 'uuid' },
        },
        'werbung.seite': { uri: 'werbung\/{werbekonto}\/seite', methods: ['PATCH'], parameters: ['werbekonto'], bindings: { werbekonto: 'uuid' } },
        'werbung.trennen': { uri: 'werbung\/{werbekonto}', methods: ['DELETE'], parameters: ['werbekonto'], bindings: { werbekonto: 'uuid' } },
        'werbung.kampagne.anlegen': { uri: 'werbung\/kampagnen', methods: ['POST'] },
        'werbung.kampagne.aendern': {
            uri: 'werbung\/kampagnen\/{kampagne}',
            methods: ['PATCH'],
            parameters: ['kampagne'],
            bindings: { kampagne: 'uuid' },
        },
        'werbung.kampagne.loeschen': {
            uri: 'werbung\/kampagnen\/{kampagne}',
            methods: ['DELETE'],
            parameters: ['kampagne'],
            bindings: { kampagne: 'uuid' },
        },
        'marke.index': { uri: 'marke', methods: ['GET', 'HEAD'] },
        'marke.speichern': { uri: 'marke', methods: ['PUT'] },
        'marke.begriff.anlegen': { uri: 'marke\/begriffe', methods: ['POST'] },
        'marke.begriff.entfernen': { uri: 'marke\/begriffe\/{begriff}', methods: ['DELETE'], parameters: ['begriff'], bindings: { begriff: 'uuid' } },
        'marke.referenz.anlegen': { uri: 'marke\/referenzen', methods: ['POST'] },
        'marke.referenz.entfernen': {
            uri: 'marke\/referenzen\/{referenz}',
            methods: ['DELETE'],
            parameters: ['referenz'],
            bindings: { referenz: 'uuid' },
        },
        'auswertung.index': { uri: 'auswertung', methods: ['GET', 'HEAD'] },
        'hwg.index': { uri: 'hwg', methods: ['GET', 'HEAD'] },
        'hwg.pruefen': { uri: 'hwg\/probe', methods: ['POST'] },
        'anzeigen.index': { uri: 'anzeigen', methods: ['GET', 'HEAD'] },
        'anzeigen.speichern': { uri: 'anzeigen', methods: ['POST'] },
        'anzeigen.freigeben': {
            uri: 'anzeigen\/{vorschlag}\/freigeben',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.verwerfen': {
            uri: 'anzeigen\/{vorschlag}\/verwerfen',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.zurueckholen': {
            uri: 'anzeigen\/{vorschlag}\/zurueckholen',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.uebersteuern': {
            uri: 'anzeigen\/{vorschlag}\/uebersteuern',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.bild.anfordern': {
            uri: 'anzeigen\/{vorschlag}\/bild',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.bild': { uri: 'anzeigen\/{vorschlag}\/bild', methods: ['GET', 'HEAD'], parameters: ['vorschlag'], bindings: { vorschlag: 'uuid' } },
        'anzeigen.schalten': {
            uri: 'anzeigen\/{vorschlag}\/schalten',
            methods: ['POST'],
            parameters: ['vorschlag'],
            bindings: { vorschlag: 'uuid' },
        },
        'anzeigen.erneut': { uri: 'anzeigen\/uebertragung\/{anzeige}', methods: ['POST'], parameters: ['anzeige'], bindings: { anzeige: 'uuid' } },
        'team.index': { uri: 'team', methods: ['GET', 'HEAD'] },
        'team.update': { uri: 'team\/{member}', methods: ['PATCH'], parameters: ['member'], bindings: { member: 'uuid' } },
        'team.deactivate': { uri: 'team\/{member}', methods: ['DELETE'], parameters: ['member'], bindings: { member: 'uuid' } },
        'team.reactivate': { uri: 'team\/{member}\/reaktivieren', methods: ['PUT'], parameters: ['member'], bindings: { member: 'uuid' } },
        'team.zwei-faktor': { uri: 'team\/{member}\/zwei-faktor', methods: ['DELETE'], parameters: ['member'], bindings: { member: 'uuid' } },
        'invitations.store': { uri: 'team\/einladungen', methods: ['POST'] },
        'invitations.resend': {
            uri: 'team\/einladungen\/{invitation}\/erneut',
            methods: ['POST'],
            parameters: ['invitation'],
            bindings: { invitation: 'uuid' },
        },
        'invitations.destroy': {
            uri: 'team\/einladungen\/{invitation}',
            methods: ['DELETE'],
            parameters: ['invitation'],
            bindings: { invitation: 'uuid' },
        },
        'audit.index': { uri: 'protokoll', methods: ['GET', 'HEAD'] },
        'backoffice.anmelden': { uri: 'backoffice\/anmelden', methods: ['GET', 'HEAD'] },
        'backoffice.anmelden.senden': { uri: 'backoffice\/anmelden', methods: ['POST'] },
        'backoffice.anmelden.code': { uri: 'backoffice\/anmelden\/code', methods: ['GET', 'HEAD'] },
        'backoffice.anmelden.code.pruefen': { uri: 'backoffice\/anmelden\/code', methods: ['POST'] },
        'backoffice.anmelden.code.erneut': { uri: 'backoffice\/anmelden\/code\/erneut', methods: ['POST'] },
        'backoffice.anmelden.code.abbrechen': { uri: 'backoffice\/anmelden\/code', methods: ['DELETE'] },
        'backoffice.index': { uri: 'backoffice', methods: ['GET', 'HEAD'] },
        'backoffice.betreiber.index': { uri: 'backoffice\/betreiber', methods: ['GET', 'HEAD'] },
        'backoffice.betreiber.store': { uri: 'backoffice\/betreiber', methods: ['POST'] },
        'backoffice.betreiber.rolle': {
            uri: 'backoffice\/betreiber\/{betreiber}\/rolle',
            methods: ['PATCH'],
            parameters: ['betreiber'],
            bindings: { betreiber: 'uuid' },
        },
        'backoffice.betreiber.deaktivieren': {
            uri: 'backoffice\/betreiber\/{betreiber}\/deaktivieren',
            methods: ['POST'],
            parameters: ['betreiber'],
            bindings: { betreiber: 'uuid' },
        },
        'backoffice.betreiber.reaktivieren': {
            uri: 'backoffice\/betreiber\/{betreiber}\/reaktivieren',
            methods: ['POST'],
            parameters: ['betreiber'],
            bindings: { betreiber: 'uuid' },
        },
        'backoffice.betreiber.zwei-faktor': {
            uri: 'backoffice\/betreiber\/{betreiber}\/zwei-faktor-zuruecksetzen',
            methods: ['POST'],
            parameters: ['betreiber'],
            bindings: { betreiber: 'uuid' },
        },
        'backoffice.betreiber.loeschen': {
            uri: 'backoffice\/betreiber\/{betreiber}',
            methods: ['DELETE'],
            parameters: ['betreiber'],
            bindings: { betreiber: 'uuid' },
        },
        'backoffice.paket': { uri: 'backoffice\/paket', methods: ['GET', 'HEAD'] },
        'backoffice.paket.store': { uri: 'backoffice\/paket', methods: ['POST'] },
        'backoffice.versand': { uri: 'backoffice\/versand', methods: ['GET', 'HEAD'] },
        'backoffice.versand.update': { uri: 'backoffice\/versand', methods: ['PUT'] },
        'backoffice.versand.probe': { uri: 'backoffice\/versand\/probe', methods: ['POST'] },
        'backoffice.versand.logo': { uri: 'backoffice\/versand\/logo', methods: ['POST'] },
        'backoffice.versand.logo.entfernen': { uri: 'backoffice\/versand\/logo', methods: ['DELETE'] },
        'backoffice.mails': { uri: 'backoffice\/mails', methods: ['GET', 'HEAD'] },
        'backoffice.mails.edit': {
            uri: 'backoffice\/mails\/{mailart}',
            methods: ['GET', 'HEAD'],
            wheres: { mailart: 'email-bestaetigen|passwort-zuruecksetzen|einladung|agentenalarm|anmeldecode|einrichtungscode' },
            parameters: ['mailart'],
        },
        'backoffice.mails.update': {
            uri: 'backoffice\/mails\/{mailart}',
            methods: ['PUT'],
            wheres: { mailart: 'email-bestaetigen|passwort-zuruecksetzen|einladung|agentenalarm|anmeldecode|einrichtungscode' },
            parameters: ['mailart'],
        },
        'backoffice.mails.destroy': {
            uri: 'backoffice\/mails\/{mailart}',
            methods: ['DELETE'],
            wheres: { mailart: 'email-bestaetigen|passwort-zuruecksetzen|einladung|agentenalarm|anmeldecode|einrichtungscode' },
            parameters: ['mailart'],
        },
        'backoffice.mails.vorschau': {
            uri: 'backoffice\/mails\/{mailart}\/vorschau',
            methods: ['POST'],
            wheres: { mailart: 'email-bestaetigen|passwort-zuruecksetzen|einladung|agentenalarm|anmeldecode|einrichtungscode' },
            parameters: ['mailart'],
        },
        'backoffice.mails.probe': {
            uri: 'backoffice\/mails\/{mailart}\/probe',
            methods: ['POST'],
            wheres: { mailart: 'email-bestaetigen|passwort-zuruecksetzen|einladung|agentenalarm|anmeldecode|einrichtungscode' },
            parameters: ['mailart'],
        },
        'backoffice.protokoll': { uri: 'backoffice\/protokoll', methods: ['GET', 'HEAD'] },
        'backoffice.show': {
            uri: 'backoffice\/{organisation}',
            methods: ['GET', 'HEAD'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'backoffice.sperren': {
            uri: 'backoffice\/{organisation}\/sperren',
            methods: ['POST'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'backoffice.entsperren': {
            uri: 'backoffice\/{organisation}\/entsperren',
            methods: ['POST'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'backoffice.gutschrift': {
            uri: 'backoffice\/{organisation}\/gutschrift',
            methods: ['POST'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'backoffice.abo': {
            uri: 'backoffice\/{organisation}\/abo',
            methods: ['POST'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'backoffice.testphase': {
            uri: 'backoffice\/{organisation}\/testphase',
            methods: ['POST'],
            wheres: { organisation: '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}' },
            parameters: ['organisation'],
        },
        'abo.edit': { uri: 'settings\/abo', methods: ['GET', 'HEAD'] },
        'abo.kasse': { uri: 'settings\/abo\/kasse', methods: ['POST'] },
        'abo.portal': { uri: 'settings\/abo\/portal', methods: ['POST'] },
        'abo.gesperrt': { uri: 'abo-gesperrt', methods: ['GET', 'HEAD'] },
        'stripe.webhook': { uri: 'webhooks\/stripe', methods: ['POST'] },
        'profile.edit': { uri: 'settings\/profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'settings\/profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'settings\/profile', methods: ['DELETE'] },
        'einfuehrung.gesehen': { uri: 'settings\/einfuehrung', methods: ['POST'] },
        'password.edit': { uri: 'settings\/password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'settings\/password', methods: ['PUT'] },
        'zwei-faktor.edit': { uri: 'settings\/zwei-faktor', methods: ['GET', 'HEAD'] },
        'zwei-faktor.destroy': { uri: 'settings\/zwei-faktor', methods: ['DELETE'] },
        'zwei-faktor.app': { uri: 'settings\/zwei-faktor\/app', methods: ['POST'] },
        'zwei-faktor.app.bestaetigen': { uri: 'settings\/zwei-faktor\/app\/bestaetigen', methods: ['POST'] },
        'zwei-faktor.email': { uri: 'settings\/zwei-faktor\/email', methods: ['POST'] },
        'zwei-faktor.email.erneut': { uri: 'settings\/zwei-faktor\/email\/erneut', methods: ['POST'] },
        'zwei-faktor.email.bestaetigen': { uri: 'settings\/zwei-faktor\/email\/bestaetigen', methods: ['POST'] },
        'zwei-faktor.einrichtung.abbrechen': { uri: 'settings\/zwei-faktor\/einrichtung', methods: ['DELETE'] },
        'zwei-faktor.codes': { uri: 'settings\/zwei-faktor\/codes', methods: ['POST'] },
        'zwei-faktor.hinweis': { uri: 'settings\/zwei-faktor\/hinweis', methods: ['POST'] },
        'tracking.edit': { uri: 'settings\/tracking', methods: ['GET', 'HEAD'] },
        'tracking.update': { uri: 'settings\/tracking', methods: ['PUT'] },
        'postfach.edit': { uri: 'settings\/postfach', methods: ['GET', 'HEAD'] },
        'postfach.update': { uri: 'settings\/postfach', methods: ['PUT'] },
        'postfach.pruefen': { uri: 'settings\/postfach\/probe', methods: ['POST'] },
        'whatsapp.edit': { uri: 'settings\/whatsapp', methods: ['GET', 'HEAD'] },
        'whatsapp.update': { uri: 'settings\/whatsapp', methods: ['PUT'] },
        'whatsapp.pruefen': { uri: 'settings\/whatsapp\/pruefen', methods: ['POST'] },
        'erscheinungsbild.edit': { uri: 'settings\/erscheinungsbild', methods: ['GET', 'HEAD'] },
        'erscheinungsbild.update': { uri: 'settings\/erscheinungsbild', methods: ['PUT'] },
        'erscheinungsbild.logo': { uri: 'settings\/erscheinungsbild\/logo', methods: ['POST'] },
        'erscheinungsbild.logo.entfernen': { uri: 'settings\/erscheinungsbild\/logo', methods: ['DELETE'] },
        'mailvorlagen.index': { uri: 'settings\/mails', methods: ['GET', 'HEAD'] },
        'mailvorlagen.signatur': { uri: 'settings\/mails\/signatur', methods: ['PUT'] },
        'mailvorlagen.edit': {
            uri: 'settings\/mails\/{mailart}',
            methods: ['GET', 'HEAD'],
            wheres: { mailart: 'eingangsbestaetigung|terminbestaetigung|erinnerung|verschiebung|absage' },
            parameters: ['mailart'],
        },
        'mailvorlagen.update': {
            uri: 'settings\/mails\/{mailart}',
            methods: ['PUT'],
            wheres: { mailart: 'eingangsbestaetigung|terminbestaetigung|erinnerung|verschiebung|absage' },
            parameters: ['mailart'],
        },
        'mailvorlagen.destroy': {
            uri: 'settings\/mails\/{mailart}',
            methods: ['DELETE'],
            wheres: { mailart: 'eingangsbestaetigung|terminbestaetigung|erinnerung|verschiebung|absage' },
            parameters: ['mailart'],
        },
        'mailvorlagen.vorschau': {
            uri: 'settings\/mails\/{mailart}\/vorschau',
            methods: ['POST'],
            wheres: { mailart: 'eingangsbestaetigung|terminbestaetigung|erinnerung|verschiebung|absage' },
            parameters: ['mailart'],
        },
        'mailvorlagen.probe': {
            uri: 'settings\/mails\/{mailart}\/probe',
            methods: ['POST'],
            wheres: { mailart: 'eingangsbestaetigung|terminbestaetigung|erinnerung|verschiebung|absage' },
            parameters: ['mailart'],
        },
        'agent.edit': { uri: 'settings\/assistent', methods: ['GET', 'HEAD'] },
        'agent.update': { uri: 'settings\/assistent', methods: ['PUT'] },
        'impersonation.store': { uri: 'impersonation', methods: ['POST'] },
        'impersonation.destroy': { uri: 'impersonation', methods: ['DELETE'] },
        'impersonation.approve': {
            uri: 'impersonation\/{session}\/freigeben',
            methods: ['POST'],
            parameters: ['session'],
            bindings: { session: 'uuid' },
        },
        'invitations.show': { uri: 'einladung\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'invitations.accept': { uri: 'einladung\/{token}', methods: ['POST'], parameters: ['token'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'login.zwei-faktor': { uri: 'login\/zwei-faktor', methods: ['GET', 'HEAD'] },
        'login.zwei-faktor.pruefen': { uri: 'login\/zwei-faktor', methods: ['POST'] },
        'login.zwei-faktor.erneut': { uri: 'login\/zwei-faktor\/erneut', methods: ['POST'] },
        'login.zwei-faktor.abbrechen': { uri: 'login\/zwei-faktor', methods: ['DELETE'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email\/{id}\/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'storage.local': { uri: 'storage\/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
        'storage.local.upload': { uri: 'storage\/{path}', methods: ['PUT'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
